// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcT1jbj0P75_q1Pgqlr9liT-lLxujqvXE',
    appId: '1:1024351849204:web:638804045bb9926c2deca1',
    messagingSenderId: '1024351849204',
    projectId: 'hash-balance-24465',
    authDomain: 'hash-balance-24465.firebaseapp.com',
    storageBucket: 'hash-balance-24465.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_5iZg-03Mc7lA9lsTxVSfWYfseEHuUe8',
    appId: '1:1024351849204:android:0354ad612091fdbf2deca1',
    messagingSenderId: '1024351849204',
    projectId: 'hash-balance-24465',
    storageBucket: 'hash-balance-24465.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVMsyljQ1zMLL2K-2m4404zF9eBKww3CE',
    appId: '1:1024351849204:ios:2d77c963c2a659082deca1',
    messagingSenderId: '1024351849204',
    projectId: 'hash-balance-24465',
    storageBucket: 'hash-balance-24465.appspot.com',
    androidClientId: '1024351849204-8tsingfnieiem4t48fkle8dcksi0rdl5.apps.googleusercontent.com',
    iosClientId: '1024351849204-a6j8lglddd5n7ff1p7mii6ar80blqbii.apps.googleusercontent.com',
    iosBundleId: 'com.example.hashBalance',
  );

}