// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZcCH-R-kUGwaxwXet0wBNtoD4pgODHTw',
    appId: '1:491242368609:web:ae17fab22f7b41b6140420',
    messagingSenderId: '491242368609',
    projectId: 'hash-balance-6ee7d',
    authDomain: 'hash-balance-6ee7d.firebaseapp.com',
    storageBucket: 'hash-balance-6ee7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK1f_lsGR6olRH4BrvXmx39R3D6K4EKgk',
    appId: '1:491242368609:android:089e401aa7c7ef07140420',
    messagingSenderId: '491242368609',
    projectId: 'hash-balance-6ee7d',
    storageBucket: 'hash-balance-6ee7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkWoOtxUzDkHm4OYcAzDojswhT1TlPtcs',
    appId: '1:491242368609:ios:b8aff2cc67235fb9140420',
    messagingSenderId: '491242368609',
    projectId: 'hash-balance-6ee7d',
    storageBucket: 'hash-balance-6ee7d.appspot.com',
    androidClientId: '491242368609-ab3u71uvqbfdcfmsjqmp2gbdo3sc3925.apps.googleusercontent.com',
    iosClientId: '491242368609-gst4rkqfg159240mn6aer0hnsompsqqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.hashBalance',
  );
}
