// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrdjnBnMmb4iM_bUzYg0WOTSvbrCMMZoQ',
    appId: '1:342717500493:web:9cdae62f99d93c34d0e004',
    messagingSenderId: '342717500493',
    projectId: 'hash-balance-official',
    authDomain: 'hash-balance-official.firebaseapp.com',
    storageBucket: 'hash-balance-official.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3tSQM2M4v8NEVN6Gs95k3-weaf3tWsjg',
    appId: '1:342717500493:android:e5b8281843ea1886d0e004',
    messagingSenderId: '342717500493',
    projectId: 'hash-balance-official',
    storageBucket: 'hash-balance-official.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsGn_1rT4o-dAdJqBtSluJqnJ9TMdzusw',
    appId: '1:342717500493:ios:3c9613ef45bdfd42d0e004',
    messagingSenderId: '342717500493',
    projectId: 'hash-balance-official',
    storageBucket: 'hash-balance-official.appspot.com',
    iosBundleId: 'com.example.hashBalance',
  );

}